repos:
  - repo: https://github.com/python/black.git
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--safe]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.3.6
        language_version: python3